# Generated by Django 5.1.7 on 2025-04-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=100, unique=True)),
                ('customer_city', models.TextField(blank=True, max_length=50, null=True)),
                ('customer_address', models.TextField(blank=True, max_length=100, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPhone',
            fields=[
                ('customer_phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
