# Generated by Django 5.1.7 on 2025-04-07 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMaintenance',
            fields=[
                ('process_maintenance_id', models.AutoField(primary_key=True, serialize=False)),
                ('eng_name', models.CharField(blank=True, max_length=100, null=True)),
                ('damage', models.TextField(blank=True, max_length=500, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessToReception',
            fields=[
                ('process_to_reception_id', models.AutoField(primary_key=True, serialize=False)),
                ('who_received', models.CharField(blank=True, max_length=100, null=True)),
                ('current_place', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('reception_id', models.AutoField(primary_key=True, serialize=False)),
                ('initial_damage', models.TextField(blank=True, max_length=500, null=True)),
                ('real_damage', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('received', models.BooleanField(default=False)),
                ('replay', models.TextField(blank=True, max_length=500, null=True)),
                ('check_feedback', models.TextField(blank=True, max_length=500, null=True)),
                ('calling_customer', models.BooleanField(default=False)),
                ('given_to_customer', models.BooleanField(default=False)),
                ('accepted', models.BooleanField(default=False)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_place', models.CharField(blank=True, max_length=100, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='attachments/%Y-%m-%d/')),
                ('receptionists', models.CharField(blank=True, max_length=100, null=True)),
                ('machines', models.CharField(blank=True, max_length=100, null=True)),
                ('calls', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
