# Generated by Django 5.1.7 on 2025-04-07 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('machine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='case_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_receptions', to='machine.machine'),
        ),
        migrations.AddField(
            model_name='reception',
            name='process_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='dashboard.processmaintenance'),
        ),
        migrations.AddField(
            model_name='reception',
            name='process_to_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='dashboard.processtoreception'),
        ),
        migrations.AddField(
            model_name='reception',
            name='who_received',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_receptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processtoreception',
            name='reception_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_to_receptions', to='dashboard.reception'),
        ),
        migrations.AddField(
            model_name='processmaintenance',
            name='reception_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_maintenances', to='dashboard.reception'),
        ),
    ]
