# Generated by Django 5.1.7 on 2025-04-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='case_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_receptions', to='machine.machine'),
        ),
        migrations.AddField(
            model_name='reception',
            name='process_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='dashboard.processmaintenance'),
        ),
        migrations.AddField(
            model_name='reception',
            name='process_to_reception',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receptions', to='dashboard.processtoreception'),
        ),
    ]
