# Generated by Django 5.1.7 on 2025-04-10 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='who_received',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_receptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='processtoreception',
            name='reception_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_to_receptions', to='dashboard.reception'),
        ),
        migrations.AddField(
            model_name='processmaintenance',
            name='reception_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_maintenances', to='dashboard.reception'),
        ),
    ]
