# Generated by Django 5.1.7 on 2025-04-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=100, unique=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_types', to='machine.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_num', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_num', models.CharField(blank=True, max_length=100, null=True)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='machine.machinetype')),
            ],
        ),
        migrations.CreateModel(
            name='MultiReceptionAndTV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_reception_and_tv', to='machine.machine')),
            ],
        ),
    ]
