# Generated by Django 5.1.7 on 2025-04-10 01:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Agent name must be at least 2 characters.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['agent_name'],
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('machine_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=100, unique=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_types', to='machine.agent')),
            ],
        ),
        migrations.CreateModel(
            name='MachineModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2, 'Model name must be at least 2 characters.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_models', to='machine.machinetype')),
            ],
            options={
                'verbose_name': 'Machine Model',
                'ordering': ['model_name'],
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_num', models.CharField(blank=True, help_text='Unique serial number for the machine (optional).', max_length=100, null=True, unique=True)),
                ('manufactured_date', models.DateField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='machine.machinemodel')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='machine.machinetype')),
            ],
            options={
                'verbose_name': 'Machine',
                'ordering': ['machine_type__machine_name', 'serial_num'],
            },
        ),
        migrations.CreateModel(
            name='MultiReceptionAndTV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_reception_and_tv', to='machine.machine')),
            ],
            options={
                'verbose_name': 'Multi Reception and TV',
                'verbose_name_plural': 'Multi Receptions and TVs',
            },
        ),
    ]
