# Generated by Django 5.1.7 on 2025-04-10 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machine', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multireceptionandtv',
            name='reception',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_reception_and_tv', to='reception.reception'),
        ),
        migrations.AlterUniqueTogether(
            name='multireceptionandtv',
            unique_together={('reception', 'machine')},
        ),
    ]
