# Generated by Django 5.1.7 on 2025-04-10 01:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('call_id', models.AutoField(primary_key=True, serialize=False)),
                ('call_type', models.CharField(choices=[('RECEIVED', 'Received'), ('CANCELED', 'Canceled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('PENDING', 'Pending')], default='RECEIVED', max_length=20)),
                ('summary', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('reception_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=255, unique=True)),
                ('initial_damage', models.TextField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('initial_tax', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('initial_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('IN_CHECK', 'In Check'), ('CHECK_FEEDBACK', 'Check Feedback'), ('CUSTOMER_CALL', 'Customer Call'), ('IN_MAINTENANCE', 'In Maintenance'), ('REFUSED', 'Refused'), ('ACCEPTED', 'Accepted'), ('WAIT_IN_RECEPTION', 'Wait In Reception'), ('GIVEN_TO_CUSTOMER', 'Given To Customer')], default='IN_CHECK', max_length=20)),
                ('current_place', models.CharField(choices=[('reception', 'Reception'), ('maintenance', 'Maintenance'), ('customer', 'Customer'), ('warehouse', 'Warehouse'), ('shipping', 'Shipping')], default='reception', max_length=20)),
                ('returned', models.BooleanField(default=False)),
                ('have_guarantee', models.BooleanField(default=False)),
                ('in_guarantee', models.BooleanField(default=False)),
                ('warranty_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('check_machine_date', models.DateTimeField(blank=True, null=True)),
                ('check_feedback_date', models.DateTimeField(blank=True, null=True)),
                ('check_feedback_description', models.TextField(blank=True, max_length=500, null=True)),
                ('refused_reason', models.TextField(blank=True, max_length=500, null=True)),
                ('refused_date', models.DateTimeField(blank=True, null=True)),
                ('maintenance_date', models.DateTimeField(blank=True, null=True)),
                ('excepted_completion_date', models.DateField(blank=True, null=True)),
                ('given_to_customer_date', models.DateTimeField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, max_length=500, null=True)),
                ('priority', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='ReceptionPhoto',
            fields=[
                ('reception_photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(upload_to='reception_photos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairNote',
            fields=[
                ('repair_note_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('status_change_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('old_status', models.CharField(choices=[('IN_CHECK', 'In Check'), ('CHECK_FEEDBACK', 'Check Feedback'), ('CUSTOMER_CALL', 'Customer Call'), ('IN_MAINTENANCE', 'In Maintenance'), ('REFUSED', 'Refused'), ('ACCEPTED', 'Accepted'), ('WAIT_IN_RECEPTION', 'Wait In Reception'), ('GIVEN_TO_CUSTOMER', 'Given To Customer')], max_length=20)),
                ('new_status', models.CharField(choices=[('IN_CHECK', 'In Check'), ('CHECK_FEEDBACK', 'Check Feedback'), ('CUSTOMER_CALL', 'Customer Call'), ('IN_MAINTENANCE', 'In Maintenance'), ('REFUSED', 'Refused'), ('ACCEPTED', 'Accepted'), ('WAIT_IN_RECEPTION', 'Wait In Reception'), ('GIVEN_TO_CUSTOMER', 'Given To Customer')], max_length=20)),
            ],
        ),
    ]
