# Generated by Django 5.1.7 on 2025-04-07 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='who_received',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_receptions', to='user.user'),
        ),
        migrations.AddField(
            model_name='calls',
            name='reception_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='reception.reception'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='reception_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reception.reception'),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='reception_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist', to='reception.reception'),
        ),
    ]
